### ISSUE TITLE
No stats for scrubs?

### ISSUE THREAD

**Issue by jparnzen** [jimsalterjrs/ioztat#37]
Perhaps more of question than an issue: Does ioztat show stats while a scrub is being performed?

I'm currently running a scrub on a pool and not seeing any read ops/stats showing up in ioztat like I would with `zpool iostat`. I'm just using a basic command of `ioztat -xy poolname 1`, and I've tried with sudo and without to no avail.

**Comment by Freaky** [comment]
No.  ioztat shows logical I/O for datasets - so things like applications performing read() and write() calls.  Scrubs are lower-level, operating on the underlying pools.

It's a bit like how if you were monitoring UFS2/ext4 I/O operations, you wouldn't see RAID rebuild I/O from GEOM/md - because it's working further down the stack.
